### ISSUE TITLE
Formating issues in WCT codebase

### ISSUE THREAD

**Issue by RosarioPulella** [dotnet/format#1145]
In windows-toolkit/WindowsCommunityToolkit/pull/3893 we discovered some changes from this tool that seemed change the code to be misleading or less clear.

**Comment by JoeRobich** [comment]
@RosarioPulella Can you provide some berfore and after examples? Also, what parameters did you pass when you invoked dotnet-format?

**Comment by RosarioPulella** [comment]
> @RosarioPulella Can you provide some before and after examples? Also, what parameters did you pass when you invoked dotnet-format? 

I'll try to get a list of examples soon. Just wanted to get this in in case I did not get a chance to.

@Nirmal4G do you know what parameters you used?

**Comment by Nirmal4G** [comment]
In the PR, the last two commits represents what you asked, the before/after changes.

Here's how I invoked `dotnet format`…

```cmd
E:\Projects\GitHub\windows-appkit
> dotnet format -wsa
```

**Comment by JoeRobich** [comment]
So, part of the fix will be updating your .editorconfig to specify the indentation behavior that you are expecting.

- Labels are being correctly formatted to be one indentation less the current indentation. 
  - [Example from the PR](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3893/commits/6701433e32a7334cc4b68a776ae562c329b8b0f9#diff-2b33ef16551541250c317b094bc72a953e32444adfd82d36003c893de29bf5e1R670)
  - [Configuration in the .editorconfig](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/d1f334a946396d97e7e17b793d589b8bc75f706c/.editorconfig#L107)
  - [Documentation for `csharp_indent_labels `](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules#csharp_indent_labels)

- Switch case blocks are being correctly formatted, as specified in your .editorconfig, to be indented. 
  - [Example from the PR](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3893/commits/6701433e32a7334cc4b68a776ae562c329b8b0f9#diff-3713dde319ca07ebd37211657dbc46bcb8894e6aaa0bb7b3d65c68cf454c7cccR740)
  - [Configuration in the .editorconfig](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/d1f334a946396d97e7e17b793d589b8bc75f706c/.editorconfig#L106)
  - [Documentation for `csharp_indent_case_contents_when_block `](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules#csharp_indent_case_contents_when_block)

The other part will be to disable formatting around blocks of code that the Roslyn formatter cannot reason about.

- Blocks of conditionally compiled code are not formatted as expected. [Example from the PR](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3893/commits/6701433e32a7334cc4b68a776ae562c329b8b0f9#diff-3b90bb258ff544d8d1e7a76fd0fbc9cc21a071c2cee62e9641b4bbf869064ccbR321)

I am not sure the Roslyn formatter would ever be able to get this correct since the code could conditionally be nested within other blocks. https://github.com/dotnet/format/issues/783 is an open request to improve formatting of code withing these conditional directives.  For the time being I would recommend using `#pragma warning disable format` and `#pragma warning enable format` around this code to disable the formatter.

**Comment by Nirmal4G** [comment]
Is there anyway to format certain blocks of code with column alignment (for a lack of a better term!)?

Example:

```cs
  var    a   = bd;
  string cfg =  e;

  Func1("123", cfg);
  Func2(  "2",   e);
```

**Comment by JoeRobich** [comment]
> Is there anyway to format certain blocks of code with column alignment (for lack of a better term!)?

The Roslyn formatter does not currently support column alignment. There are several open issues tracking support for this type of formatting https://github.com/dotnet/roslyn/issues/51389, https://github.com/dotnet/roslyn/issues/28729, and https://github.com/dotnet/roslyn/issues/38241. Please vote them up and add any specific requirements that you might have.

I am going to mark this issue as closed. Please reopen it if I didn't address all the issues you saw in your PR or if there are issues with indentation after updating the .editorconfig.
