### ISSUE TITLE
[Feature Request] --fix-style and --fix-analyzers support for --folder

### ISSUE THREAD

**Issue by DoubleLoopAndy** [dotnet/format#1158]
Unity generates project files locally that include full file path references to the Unity assemblies and so aren't suitable for committing to version control. While I can run without --folder locally, I want to have a GitHub Action run on pull requests to check that the style and analyzers are correct without the projects.

--fix-style and --fix-analyzers currently report an unsupported error when used with --folder
https://github.com/dotnet/format/commit/0dcaf98d4ad5aeb4f3904f4df372dee72222159b

**Comment by jmarolf** [comment]
how is Unity compiling these files? We could make up a set of commandline options to use without a project, but they won't work. We nned to somehow know about the unity assemblies

**Comment by DoubleLoopAndy** [comment]
From the IDE perspective, Unity generates projects with references to Unity assemblies. Because these projects include references to local paths (depending on where the developer installed Unity), they aren't suitable for committing to version control.

If you're not using an IDE, Unity compilation during its import/build process must be generating temporary projects/solutions  - at least they aren't visible in a location near the code.

If it's just not workable without a project/solution for technical reasons, then you can close the request and I can pursue this from another angle - likely setting up Unity to generate temporary projects/solutions in a GitHub Action and then using those for the dotnet format run.

**Comment by JoeRobich** [comment]
> If it's just not workable without a project/solution for technical reasons, then you can close the request and I can pursue this from another angle 

We need a project or solution when running analyzers because they are used to resolve library references (framework, NuGet, other projects). We could fallback and treat all the code files as if they were compiling against NET Standard 2.0, but then every type you use from Unity references would be unresolved and we wouldn't know what to make of them.

> likely setting up Unity to generate temporary projects/solutions in a GitHub Action and then using those for the dotnet format run.

This would be the right solution. If you can get it working and are able to, please share a snippet for others who find this issue.

Going to close this one since there isn't any way for us to get this right.

**Comment by DoubleLoopAndy** [comment]
Thanks. 

It makes sense for analyzers, less so for style fixes, but I haven't looked at the internals of dotnet format to understand if/how it depends on a project/solution to fix style issues.

**Comment by JoeRobich** [comment]
@DoubleLoopAndy Many code style analyzers and fixes rely on having complete semantic information about your code. If types are not able to be resolved, then the structure of code cannot always be inferred. Take `Name.IsMatch` for instance. Without knowing what type `Name` is, the analyzer won't be able to know whether `IsMatch` is a property, static field, name of a function, etc...

**Comment by DoubleLoopAndy** [comment]
Thanks, that makes sense! I figured a lot of the syntax formatting options would be code agnostic but I can appreciate that it may just be easier to lump together everything but whitespace settings.

**Comment by jmarolf** [comment]
We can take a look at the code formatting options. We could attempt to break out ones that are purely syntactic (expression-bodied members could be handled this way). When they were originally written this wasn't a concern, we would need to open up an issue on dotnet/roslyn to track this. To give some idea of the work inolved:

- Var Preferences: needs semantic info in order to follow C# spec name lookup rules
- Expression Bodied Members: can be purely syntactic
- Pattern Matching: Needs semantic info to know if pattern matching will change semantics
- Null Checking Preferences: Need semantic info 
- Modifier: can be purely syntactic 
- Code Block Preferences: can be purely syntactic 
- Expression Level Preferences: can be purely syntactic
- Using Directive Preferences: can be purely syntactic 
- New Line Preferences: can be purely syntactic

**Comment by DoubleLoopAndy** [comment]
That would be really nice to have at some point. Thanks for breaking that down!
