### ISSUE TITLE
WPF projects don't compile

### ISSUE THREAD

**Issue by virzak** [dotnet/format#1337]
Steps to reproduce:

```sh
mkdir WpfFormat
cd WpfFormat
dotnet new wpf
dotnet format --verify-no-changes
```

The resulting error is:

`MainWindow.xaml.cs(25,13): error CS0103: The name 'InitializeComponent' does not exist in the current context [WpfFormat.csproj]`

**Comment by DavidZidar** [comment]
I just upgraded to .NET 6 RTM and it seems that dotnet format does work with WPF now even though the fixes above hasn't been merged yet.

When formatting one project I did get the following incorrect error though:
```
MainView.xaml.cs(200,40): error CS1503: Argument 1: cannot convert from 'MyApp.Views.MainView' to 'System.Windows.DependencyObject'
```

This seemed to be caused by the fact that the partial class in my `MainView.xaml.cs`-file did not have an explicit base class set, I was able to work around the issue by adding the same base class as specified in the generated part of the partial class.

**Comment by virzak** [comment]
This works now:

```pwsh
mkdir WpfFormat
cd WpfFormat
dotnet new wpf
dotnet new tool-manifest
dotnet tool install dotnet-format --version 8.0.422703 --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json
dotnet tool run dotnet-format --verify-no-changes
```

The error you might get in AssemblyInfo is easily corrected.
