### ISSUE TITLE
How can I share .editorconfig files between projects?

### ISSUE THREAD

**Issue by justinmchase** [dotnet/format#1554]
I want to make a nuget package which has an editorconfig file in it and add a reference to that project from various applications and have them all pickup the common editor config from that shared library.

I'm just wondering, where is `dotnet-format` looking for editorconfig files? Any advice on how to add a config file from a dependency would be very helpful!

**Comment by justinmchase** [comment]
I see here the code that seems to be finding the editor config files:
https://github.com/dotnet/format/blob/master/src/Utilities/EditorConfigFinder.cs

If I put a file inside of my `src` folder I see it picks it up:
```
> dotnet-format -v d
  The dotnet runtime version is '6.0.3'.
  Formatting code files in workspace '/Users/jchase24/code/dotnet-reco/dotnet-reco.csproj'.
    Determining projects to restore...
  All projects are up-to-date for restore.
  Project dotnet-reco is using configuration from '/Users/jchase24/code/dotnet-reco/.editorconfig'.
  Project dotnet-reco is using configuration from '/Users/jchase24/code/dotnet-reco/src/.editorconfig'. <-- its loaded
  Project dotnet-reco is using configuration from '/Users/jchase24/code/dotnet-reco/obj/Debug/net6.0/dotnet-reco.GeneratedMSBuildEditorConfig.editorconfig'.
  Project dotnet-reco is using configuration from '/usr/local/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/analyzers/build/config/analysislevel_6_default.editorconfig'.
  Running 8 analyzers on dotnet-reco.
  Running 170 analyzers on dotnet-reco.
  Formatted 0 of 55 files.
  Format complete in 10196ms.
```

But if I just manually drop a file into my `bin/Debug/net6.0` folder (simulating what a referenced dependency might do) then it does not load that file for some reason 🤔

**Comment by justinmchase** [comment]
Here is deeper down in Roslyn:
https://github.com/dotnet/roslyn/blob/master/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ProjectExtensions.cs#L51-L54

>                // Currently, we use a simple heuristic to find existing .editorconfig file.
>                // We start from the directory of the source file where the diagnostic was reported and walk up
>                // the directory tree to find an .editorconfig file.
>                // In future, we might change this algorithm, or allow end users to customize it based on options.

**Comment by xt0rted** [comment]
If you want to share these settings across projects you can package them up with nuget. I've tried to do this but always hit issues because of how these files get resolved (I commented about this earlier in the issue you linked).

For now I'm putting these files in a root `/analysis` folder and loading them as a pre-compile step. I have to manually sync them across projects, but at least they're in one spot. Hopefully one day we get a setup like ESLint has so this all becomes a lot easier.

This project has the setup I'm using, the heart of it is in [`Directory.Build.targets`](https://github.com/xt0rted/tailwindcss-tag-helpers). I'll be publishing an updated version of the configs sometime this week, but loading them stays the same.
