### ISSUE TITLE
`dotnet format style` reports "Unable to fix IDE0005" but it actually fixes it.

### ISSUE THREAD

**Issue by TAGraves** [dotnet/format#1611]
When we run `dotnet format style` on an M1 Mac in our project with `IDE0005` set to warn and with a file that has an unused `using` statement, the unused `using` statement is removed but `Unable to fix IDE0005. No associated code fix found.` is logged out.

Here's a very simple reproduction: https://github.com/TAGraves/dotnet-format-IDE0005-reproduction/tree/main

**Comment by JoeRobich** [comment]
I believe this is fixed in our development builds which have been inserted into the next versions of the .NET SDK.

We have always had a separate formatter which fixed IDE0005 (Unnecessary Imports). When changing it from a whitespace formatter to a code style formatter, it started running after code style analysis. That is why you began seeing the `Unable to fix` message logged by the code style formatter.

With this change - https://github.com/dotnet/format/commit/362295d37e912da40a993805f67ee54f29f82cc1 - we removed the separate formatter and added code to work around the way Roslyn uses an internal diagnostic id for the remove unnecessary import code fix.

You can verify this is fixed by installing our development build as a global tool. To invoke the global tool be sure to include the hyphen `dotnet-format ...options`.

```
dotnet tool install -g dotnet-format --version "6.*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json
```

**Comment by TAGraves** [comment]
Thanks, @JoeRobich! I can confirm that the development build fixes it. Great to hear!
