### ISSUE TITLE
`dotnet-format -w` does not fix whitespace issue IDE2002

### ISSUE THREAD

**Issue by jeremysalwen** [dotnet/format#1823]
I am using `dotnet-format` 5.1.250801+4a851ea9707f87d381166c2fc2b2d4b58a10a222

In my `.editorconfig` I have:
```
dotnet_diagnostic.IDE2002.severity = warning
...
csharp_style_allow_blank_lines_between_consecutive_braces_experimental = false
```
In VS Code, I get the warning `Consecutive braces must not have blank line between them [AdminSuite, AdminSuite]`.  However, formatting in VS Code does not fix it, and when I run
```
> dotnet-format -w
```
from the command line, it does not fix the issue either.  Note that if I run
```
> dotnet-format -s
```
It *does* fix it.

This seems like a bug, since `dotnet-format -w` should fix whitespace issues, including this one.

**Comment by sharwell** [comment]
Note that the only diagnostic ID covered by `-w` is IDE0055 (Fix Formatting). The rule mentioned above was implemented as a separate code style rule in https://github.com/dotnet/roslyn/pull/50358, and is not integrated into the formatter. Resolving as external since dotnet/roslyn controls the breakdown of rules handled by the formatting engine.
