### ISSUE TITLE
global.json documentation

### ISSUE THREAD

**Issue by collinstevens** [dotnet/format#1905]
The [global.json](https://github.com/dotnet/format/blob/main/global.json) specifies a tools property and looks to require a minimum visual studio version, where is this additional schema documented?

I don't see the tools property on https://learn.microsoft.com/en-us/dotnet/core/tools/global-json#globaljson-schema.

**Comment by JoeRobich** [comment]
dotnet-format uses the [dotnet/arcade](https://github.com/dotnet/arcade) SDK for its build infrastructure. dotnet/arcade defines non-standard global.json properties which it uses ([see tools.ps1](https://github.com/dotnet/arcade/blob/main/eng/common/tools.ps1)).

I would suggest sticking with standard config locations such as dotnet-tools.json, since tools like dependabot are able to help with updates.
