### ISSUE TITLE
Need to remove RazorCompiler dependency when upgrading to Roslyn 4.10.0

### ISSUE THREAD

**Issue by mthalman** [dotnet/format#2075]
Roslyn deleted the Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler package in https://github.com/dotnet/roslyn/pull/71579. But format still has references to it that need to be removed:

https://github.com/dotnet/format/blob/20369580942455657954cb20d0cfaa0a7662a6ff/Directory.Packages.props#L40

https://github.com/dotnet/format/blob/20369580942455657954cb20d0cfaa0a7662a6ff/src/dotnet-format.csproj#L39

This currently isn't broken because format still has a dependency on Roslyn 4.9.0; the deletion is in 4.10.0

**Comment by sharwell** [comment]
This seems like an automatic maintenance task that will occur during a dependency update. Is there a reason why we need to track it separately? It seems like even once this issue is fixed, it will likely remain open as the author of the pull request to update dependencies wouldn't be aware of its existence.

**Comment by mthalman** [comment]
This was logged because it required a patch in the installer repo to get source build working since it uses the latest version of Roslyn in source build. When creating a patch, we need to reference an existing issue or PR to track the work so that it ensures the underlying issue gets resolved. Anyway, this has been fixed and the patch was removed in https://github.com/dotnet/installer/pull/18641. Closing.
