### ISSUE TITLE
Please clarify if this tool is actively supported / worked on

### ISSUE THREAD

**Issue by riverar** [dotnet/format#2097]
Hello!

We’re currently modernizing our extensive code-base and are eager to utilize `dotnet format`. However, we’ve encountered some unexpected behavior with the tool from the get-go (for instance, #2086) and are trying to determine if there will be any forthcoming fixes that would facilitate our continued use of the tool. Given that the number of repository issues is already approaching 200, with some dating back to 2019, we’re beginning to perceive this tool as more of a side project rather than something that’s ready for production use or in the main "dotnet dev loop" so to speak.

Clarification of the intentions regarding the GitHub repository will greatly assist us in planning our future development efforts. Thanks in advance!

cc: @shanselman

**Comment by arkalyanms** [comment]
Thanks for bringing this up. We are a bit short staffed and fixes to dotnet format has been slowed down, but we should be able to catch up towards the back end of net8 previews. 

#2086 in particular looks immediately actionable and assigned to @sharwell for investigation.

**Comment by sharwell** [comment]
We don't have a great answer here, since we do care about this feature and would like to be able to dedicate more resources to it. The team that would generally be responsible for working on this repository recently had members pulled to a different team based on business needs (totally outside our control), leaving us particularly short-staffed in this area.

I can follow up on the linked issue separately.
