### ISSUE TITLE
Inconsistent results with dotnet format analyzers

### ISSUE THREAD

**Issue by verdie-g** [dotnet/format#2211]
Given this project
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.2.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
```

```csharp
using NUnit.Framework;

Assert.AreEqual(1,
    0);
```

Running
```
dotnet format analyzers Test.csproj --no-restore --verbosity normal --severity info --diagnostics NUnit1002 NUnit1021 NUnit1026 NUnit2001 NUnit2002 NUnit2003 NUnit2004 NUnit2005 NUnit2006 NUnit2007 NUnit2010 NUnit2011 NUnit2012 NUnit2013 NUnit2014 NUnit2015 NUnit2016 NUnit2017 NUnit2018 NUnit2019 NUnit2022 NUnit2027 NUnit2028 NUnit2029 NUnit2030 NUnit2032 NUnit2033 NUnit2034 NUnit2035 NUnit2036 NUnit2037 NUnit2038 NUnit2039 NUnit2040 NUnit2043 NUnit2044 NUnit2046 NUnit2047 NUnit2048 NUnit2049 NUnit2050
```
will sometimes give this result
```csharp
using NUnit.Framework;

Assert.That(    1, Is.EqualTo(0));
```

but other times
```csharp
using NUnit.Framework;

Assert.That(1, Is.EqualTo(0));
```

I noticed that the issue does not occur with just
```
dotnet format analyzers Test.csproj --no-restore --verbosity normal --severity info --diagnostics NUnit2005
```

Could you help me confirm this is an issue with `dotnet-format` and not NUnit.Analyzers?

**Comment by JoeRobich** [comment]
The issue seems to be the way the NUnit2005 and NUnit2007 fixers interact. The NUnit2007 fixer wants to swap the arguments to AreEqual and when it does it also moves the whitespace trivia. This is why there are 4 spaces moved from the second line to the start of the argument list. Then the NUnit2005 fixer changes which method is invoked. Those two sets of changes merge into one or the other result you are seeing. If the NUnit2007 fixer handled the whitespace trivia correctly when reordering arguments, I do not think you would be seeing this behavior.

**Comment by verdie-g** [comment]
Thanks for the investigation! I'll try working on a fix in NUnit.
