### ISSUE TITLE
dotnet-format in WSL2 doesn't recognise a cs file

### ISSUE THREAD

**Issue by hangjit-domain** [dotnet/format#610]
I'm running the following command in Ubuntu 18 (WSL2) but the program doesn't seem to recognise the cs file.

![image](https://user-images.githubusercontent.com/52148253/76714946-14c1b200-677e-11ea-9747-a177d7ce4580.png)

I installed the tool using the following command.
`/usr/bin/dotnet tool install dotnet-format --tool-path ~/dotnet`

I've tried other variations of the command with quotes but no luck.
```
~/dotnet/dotnet-format --files "ShortlistService.cs"
~/dotnet/dotnet-format --files 'ShortlistService.cs'
```

**Comment by jmarolf** [comment]
@hrai-domain does this command succeed from a normal windows command prompt?

**Comment by hrai-domain** [comment]
@jmarolf no. The formatter resorts to formatting the solution when running the command from git bash.

It's the same from command prompt as well.

`Formatting code files in workspace 'C:\dev\xxxxx\xxx.sln'.`

**Comment by jmarolf** [comment]
@JoeRobich what is the correct syntax for only formatting a single file?

**Comment by JoeRobich** [comment]
dotnet format always requires a workspace to work from. Workspaces are specified with either the `--workspace | -w` (solution or project file) or `--folder | -f` (folder) flags. In the absence of of a specified workspace we fallback to searching the current directory for a solution or project file (similar to other dotnet commands). 

Since you just want to format a single file, you can use the folder flag and specify the current directory like so `~/dotnet/dotnet-format -f . --files ShortlistService.cs`. * Note that the files list is comma separated relative paths in 3.x and space separated globs in 4.x

**Comment by jmarolf** [comment]
@JoeRobich should we change it so the `--files` flag implies the folder flag if not present?

**Comment by JoeRobich** [comment]
Closing this issue as we've updated documentation on how to filter files - https://github.com/dotnet/format/tree/master/docs#filter-files-to-format. Since we've reworked the options in our nightly build, it is required to pass the `--folder|-f` flag to specify working with the files directly. Please let us know if you have any suggestions for how to improve the documentation.
