### ISSUE TITLE
Formatting without a workspace file

### ISSUE THREAD

**Issue by qubitz** [dotnet/format#642]
What are the limitations of using dotnet-format without a .csproj or .sln?

For context, I'm developing a package repo that cannot be compiled directly without some pre- formatting magic. I'd really like to have dotnet-format run on pull request and was wondering what limitations I'd run into if I stuck to running dotnet-format with the ```--folder``` option.

**Comment by JoeRobich** [comment]
At the moment there is no difference in how dotnet format works when working with a workspace (.csproj or .sln) or a folder. That is because the rules for the changes we are making at the moment can be determined by syntax.

However, the eventual goal is to support the Roslyn code style analyzers and fixes which require semantic information that may need to take into account data stored in .csproj files such as SDK & NuGet package references. At that point, running with the folder option will give the same behavior as today since it is missing that extra information.

**Comment by qubitz** [comment]
Ah I see, thanks for the detailed explanation. Are there any [visual studio .editorconfig rules](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-formatting-conventions?view=vs-2019) that need this kind of semantic information?

**Comment by JoeRobich** [comment]
@qubitz All rules other than whitespace require additional information. You can see the list of unsupported code style rules here - https://github.com/dotnet/format/blob/master/docs/Unsupported-Code-Style-options.md
