### ISSUE TITLE
VSCode extension?

### ISSUE THREAD

**Issue by snebjorn** [dotnet/format#648]
I was unable to find a VSCode format extension that uses dotnet format.
https://marketplace.visualstudio.com/search?term=dotnet%20format&target=VSCode&category=All%20categories&sortBy=Relevance

Does anyone know if something is being worked on?
Is it something the team is planning on?

**Comment by JoeRobich** [comment]
@snebjorn The C# extension for VS Code already supports .editorconfig and CodeStyle analysis. Set `"omnisharp.enableRoslynAnalyzers"` and `"omnisharp.enableEditorConfigSupport"` to true in your settings. They are working on adding FixAll support too (https://github.com/OmniSharp/omnisharp-roslyn/pull/1581).

**Comment by snebjorn** [comment]
Excellent. Forgive me. Another question.

Is #590 about dotnet-format using roslyn to format so they're consistent?

**Comment by JoeRobich** [comment]
We already use Roslyn to format so that experience whether from the command-line with dotnet format, inside VS, or using VS Code with C# extension should be the same. That issue is about moving to Roslyn's editorconfig parsing support, which has additional features for configuring Analyzer severity, which we will need when we add Analyzer support.

**Comment by snebjorn** [comment]
Most outstanding!

**Comment by steveoh** [comment]
I am struggling to make this work. Is anyone successfully making this work for them?

**Comment by JoeRobich** [comment]
@steveoh If you are having difficulty with the C# extension for VS Code, please open a ticket at https://github.com/OmniSharp/omnisharp-vscode/issues providing all the requested logs.
